In [ ]:
from __future__ import print_function
import torch

pytorch チュートリアル  
[公式doc](http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) 
[参考](https://qiita.com/kenchon/items/b9a50ed0b48584453b99)
- What is PyTorch?
- Autograd: automatic differentiation  


In [ ]:
x = torch.Tensor(5, 3)  # 初期化なし
x

In [ ]:
x = torch.rand(5, 3)  # ランダムで初期化
x

In [ ]:
x.size()

# 演算

In [ ]:
# 加算 1
y = torch.rand(5, 3)
x + y

In [ ]:
# 加算 2
result = torch.Tensor(5, 3)      # make empty (5, 3) Tensor
torch.add(x, y, out = result)    # input x + y to Tensor
result

In [ ]:
# 加算 3
y.add_(x)     # "add_(x)" -> y = y + x 
y

## note
基本的に，演算の関数の後に _ がついているものは代入の操作を表す。

# Torch.Tensorとnumpyの変換

In [14]:
# torch から numpy に変換
a = torch.ones(5)
b = a.numpy()
print(a, type(a))
print(b, type(b))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [15]:
# ここで，面白いことに…
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
# numpy から torch に変換
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# autogradとVariable

## autograd
autogradパッケージ: Tensorの全ての演算に対して自動微分を行うためのパッケージ．
define-by-run(順伝播のコードを書くだけで逆伝播を定義する)を実現している．

## autogradのクラス
### Variable
autograd.Variableが，autogradの中心的なパッケージである．
VariableはTensorのラッパーであり，Tensorのほぼ全ての演算が含まれている．
ネットワークを定義してしまえば，.backward()を呼び出すだけで勾配計算を自動的に行うことができる．

.data  生データにアクセスできる
.grad  勾配

### Function
VariableとFunctionは内部でつながっていて，この２つによってニューラルネットワークのグラフが構築される．このグラフにニューラルネットの計算の全ての履歴が残る．

生成されたvariableのそれぞれに `.grad_fn` という属性があり，この属性によってどのFunctionによってvariableが生成されたのかを参照できる。ただし，ユーザによって作られたvariableの場合grad_fnは `None` となる。

In [18]:
import torch
from torch.autograd import Variable

In [46]:
x = Variable(torch.ones(2, 2), requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [47]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [22]:
# 何らかの演算の後に生成されたvariableには属性grad_fnが付与される
y.grad_fn

In [48]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


# 勾配計算

いよいよ逆伝播の計算です。  
次に行うout.backward()は，` out.backward(torch.tensor([1.0]))` と等価です。

In [49]:
out.backward()

In [50]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])